# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corn_husker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player', models.CharField(max_length=30)),
                ('Att', models.IntegerField()),
                ('Avg', models.FloatField()),
                ('TD', models.IntegerField()),
            ],
        ),
    ]
