# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_data', '0002_remove_corn_husker_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='corn_husker',
            name='Player',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
