# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_data', '0004_data_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='corn_husker',
            name='Yrds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
